CUDA_VISIBLE_DEVICES=1 python3 train.py \
    --dataset_path ../../dataset/train/lora/daiyu_all.json \
    --model_path /home/gpt/llm/chatglm2-6b \
    --base_model ChatGLM2-6B\
    --lora_rank 8 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --max_steps 2400 \
    --save_steps 240 \
    --save_total_limit 10 \
    --learning_rate 1e-4 \
    --fp16 \
    --remove_unused_columns false \
    --logging_steps 10 \
    --output_dir ../../dataset/output_daiyu_all